# GitLab CI/CD Pipeline Configuration for Plato

# Define stages
stages:
  - test

# Simple test job to verify pipeline works
test:
  stage: test
  image: node:20-alpine
  script:
    - echo "Pipeline is working!"
    - node --version
    - npm --version